name: Build

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/pmsfit/fmi3-wasm-devcontainer
          cacheFrom: ghcr.io/pmsfit/fmi3-wasm-devcontainer
          push: always
          runCmd: |
            cmake --preset wasm
            cmake --build --preset wasm --target run-all-examples

      - name: Upload FMU artefacts
        uses: actions/upload-artifact@v7
        with:
          name: fmus
          path: build/*.fmu

      - name: Upload runner binary artefacts
        uses: actions/upload-artifact@v7
        with:
          name: runners
          path: |
            build/adder-fmu-c-runner-build/adder-fmu-c-runner
            build/adder-fmu-rust-runner-build/adder-fmu-rust-runner
